---

language: python

python:
  - 2.7
  - 3.5
  - 3.6

matrix:
  fast_finish: true

script:
  - pip install ansible flake8
  - flake8
  - python -m unittest -v tests.test_config_encoders

notifications:
  email: false
